apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app-container
        image: ${appbuild}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-volume
          mountPath: /data
      volumes:
      - name: app-volume
        emptyDir: {}
